## 用本地配置
server:
  port: 8030 # 启动端口
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  application:
    name: bpm-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    filters: stat
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:static/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true

mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  config: classpath:config/logback-${spring.profiles.active}.xml

com:
  quinn-service:
    redis:
      maxActive: 8
      maxIdle: 8
      maxWait: -1
      minIdle: 0
      timeout: 2000
      cache:
        name: ming_cloud
      keys:
        namespace: "ming_cloud:"
        normalize: true

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    max_idle_per_key: 5
