## 用本地配置
server:
  port: 8030 # 启动端口
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  application:
    name: bpm-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    filters: stat
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:static/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true

mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  config: classpath:config/logback-${spring.profiles.active}.xml

com:
  quinn-service:
    cache:
      session-cache-name:
        redisByteCacheAllService
      # ehCacheAllService
      main-cache-name:
        redisCacheAllService
      # ehCacheAllService
      degree-cache:
        item-map:
          ehCacheAllService: 500
          redisCacheAllService: 0
      redis:
        maxActive: 1000
        maxIdle: 1000
        maxWait: -1
        minIdle: 0
        timeout: 2000
        keys-namespace: "ming_cloud:"
        keys-normalize: true
      ehcache:
        config-url: classpath:config/ehcache.xml
        cache-name: ming_cloud
        keys-namespace: "ming_cloud:"
    mq:
      rabbitmq:
        auto-listen: true
        thread-pool-size: 2
        serialize-type: 1
        max-channels: 25
    filter:
      config:
        filter-items:
          - key: anon
            url-pattens:
              - /
              - /login
              - /logout
              - /has-right
              - /wechart
              - /favicon.ico
              - /css/**
              - /js/**
              - /image/**
              - /images/**
              - /resources/**
              - /static/**
              - /cds/**
              - /anon/**
              - /users/session/**
              - /csrf
              - /swagger-ui.html
              - /swagger**
              - /swagger-resources/**
              - /v2/api-docs
              - /v2/api-docs/**
              - /webjars/**
              - /error
              - /configuration/**
              - /druid/**
              - /sso/**
              - /tenant/**
              - /url/**
              - /restful/**
              - /**/*-restful
          - key: intranet
            filter-name: intranetFilter
            url-pattens:
              - /framework/**
          - key: pathMatch
            filter-name: pathMatchPermissionFilter
            url-pattens:
              - /**
    mock-auth:
      disabled: false
      auth-infos:
        - principal: admin
          # a1234567
          credentials: A8831CF98237CE40525B0A3591CB45CD
          principals:
            "1001":
              key: 1001
              name: "Factory 001"
              rolesMap:
                FUNCTION:
                  - admin_f
                DATA:
                  - admin_d
              permissionsMap:
                INTERFACE:
                  - "*"
                MENU:
                  - script-info
            "1002":
              key: 1002
              name: "Factory 002"
              rolesMap:
                FUNCTION:
                  - admin
        - principal: guest
          # 123456
          credentials: 76710EED9ED3278801B698077AD60E98
          principals:
            "1001":
              key: 1001
              name: "Factory 001"
              rolesMap:
                FUNCTION:
                  - admin
  ming-cloud:
    core:
      auth:
        resolver-for-message: true
    bpm:
      diagram:
        font-name:
          activity: "宋体"
          label: "宋体"
          annotation: "宋体"
        color:
          active: -7667712
          history: -12799119
        image:
          type: "png"

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    max_idle_per_key: 5
