## 用本地配置
server:
  port: 8030 # 启动端口
  application:
    name: quinn-service

spring:
  profiles:
    active: dev
  datasource:
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    prefix: classpath:static/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true

mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  config: classpath:config/logback-${spring.profiles.active}.xml

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 212.64.54.213:22122
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    max_idle_per_key: 5

---
# 开发环境
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://212.64.54.213:3306/bpm7?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: ENC(HuL3vo8BrtcMmRuIXyWOIq8FR/sYllGJ32sOrzLSwms=)
    password: ENC(/feKNRSDLzSmS7YkgInHstEYw+RffB0sW3pfINwfNfsnXWud7whrlw==)
    filters: stat
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxOpenPreparedStatements: 20

---
# 测试环境
spring:
  profiles: qas

---
# 生产环境
spring:
  profiles: prd
