# 开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://212.64.54.213:3306/bpm7?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: ENC(05CD2AB2E85FDA5F41B894CB00EF6112)
    password: ENC(F1B4781AF70446F7A539E012B451CC9D)

fdfs:
  tracker-list:
    - 212.64.54.213:22122

com:
  quinn-service:
    licence:
      path: classpath:licence/ming-cloud_licence.lic
    redis:
      host: 212.64.54.213
      port: 6379
      password: ENC(216902373776ACD3EA504C86A1EC67E9)
      database: 0
